version: "3.8"

services:
  backend:
    build:
      context: ./backend    # Adjust if your backend code is in a 'backend' folder
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app    # Optional: mount code for live reloading
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend   # Adjust if your frontend code is in a 'frontend' folder
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app    # Optional: mount code for live reloading
